import { useEffect, useRef } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { session, fmtInt, fmtClock, addSecret } from '../../store/session';
import { game } from '../../store/game';
import { useTilt } from '../../hooks/useMagnetic';
import { driftCursor } from '../Cursor';
import { audio } from '../../audio/engine';
import { device } from '../../utils/device';

function Card({ n, k, children, note }: { n: string; k: string; children: React.ReactNode; note: string }) {
  const ref = useRef<HTMLElement>(null);
  useTilt(ref, 5);
  return (
    <article className="card" ref={ref}>
      <span className="card-k mono">
        <span>{n}</span>
        <span>{k}</span>
      </span>
      <span className="card-v display">{children}</span>
      <span className="card-n mono">{note}</span>
    </article>
  );
}

export default function Memory() {
  const root = useRef<HTMLElement>(null);
  const dist = useRef<HTMLSpanElement>(null);
  const dir = useRef<HTMLSpanElement>(null);
  const hes = useRef<HTMLSpanElement>(null);
  const dis = useRef<HTMLSpanElement>(null);
  const glyph = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    const el = root.current!;
    let seen = false;
    const ctx = gsap.context(() => {
      gsap.fromTo(
        '.card',
        { clipPath: 'inset(100% 0% 0% 0%)', y: 40 },
        {
          clipPath: 'inset(0% 0% 0% 0%)',
          y: 0,
          duration: 1.3,
          ease: 'expo.out',
          stagger: 0.12,
          scrollTrigger: { trigger: '.mem-cards', start: 'top 80%', once: true },
        },
      );
      gsap.fromTo('.mem-title .tl', { yPercent: 100 }, { yPercent: 0, duration: 1.4, ease: 'expo.out', stagger: 0.1, scrollTrigger: { trigger: el, start: 'top 70%', once: true } });
      ScrollTrigger.create({
        trigger: el,
        start: 'top 45%',
        once: true,
        onEnter: () => {
          if (seen) return;
          seen = true;
          game().say('user', 'still unaware.');
          if (!device.touch)
            setTimeout(() => {
              driftCursor();
              setTimeout(() => game().say('observer', 'sorry. that was me.'), 1300);
            }, 4200);
        },
      });
    }, el);

    const id = setInterval(() => {
      if (dist.current) dist.current.textContent = fmtInt(session.cursorDistance);
      if (dir.current) dir.current.textContent = session.scrollDir;
      if (hes.current) hes.current.textContent = session.longestStill.toFixed(1);
      if (dis.current)
        dis.current.textContent =
          session.firstDisobedience != null ? fmtClock(session.firstDisobedience) : session.firstWarningObeyed ? 'NONE' : '—';
    }, 110);
    return () => {
      ctx.revert();
      clearInterval(id);
    };
  }, []);

  const findGlyph = () => {
    if (session.glyphFound) return;
    session.glyphFound = true;
    addSecret('glyph');
    audio.chime();
    glyph.current?.classList.add('is-found');
    game().say('observer', 'you were not supposed to find that.');
  };

  return (
    <section className="sec mem" id="memory" ref={root}>
      <div className="sec-label mono">
        <span>02</span>
        <span>Memory</span>
      </div>
      <h2 className="display mem-title">
        <span className="tl-mask">
          <span className="tl">I remember</span>
        </span>
        <span className="tl-mask">
          <span className="tl">
            <em>everything you did.</em>
          </span>
        </span>
      </h2>
      <div className="mem-cards">
        <Card n="01" k="Cursor moved" note="live · this session">
          <span ref={dist}>0</span>
          <small>px</small>
        </Card>
        <Card n="02" k="Scroll direction" note="live">
          <span ref={dir}>—</span>
        </Card>
        <Card n="03" k="Hesitation" note="longest stillness">
          <span ref={hes}>0.0</span>
          <small>sec</small>
        </Card>
        <Card n="04" k="First disobedience" note="since arrival">
          <span ref={dis}>—</span>
        </Card>
      </div>
      <div className="mem-foot">
        <p className="mono fine">
          Nothing here leaves this tab. Every value was generated by you, just now, and is forgotten when you close it.
        </p>
        <button className="glyph" ref={glyph} onClick={findGlyph} aria-label="A small symbol">
          ⌬
        </button>
      </div>
    </section>
  );
}
