import * as THREE from 'three';

export const FONT = {
  serif: '"Instrument Serif", "Times New Roman", serif',
  sans: 'Inter, system-ui, sans-serif',
  mono: '"IBM Plex Mono", ui-monospace, monospace',
};

export const COLOR = {
  bg: '#080808',
  bg2: '#0D0D0F',
  text: '#F4F1EA',
  muted: '#8D8D8D',
  red: '#FF2E2E',
  violet: '#7C5CFF',
  cyan: '#00F0FF',
};

export async function loadFonts() {
  const specs = [
    `400 100px ${FONT.serif}`,
    `italic 400 100px ${FONT.serif}`,
    `400 20px ${FONT.sans}`,
    `500 20px ${FONT.sans}`,
    `400 20px ${FONT.mono}`,
  ];
  try {
    await Promise.race([
      Promise.all(specs.map((s) => document.fonts.load(s))),
      new Promise((r) => setTimeout(r, 2500)),
    ]);
  } catch {
    /* fall back to system fonts */
  }
}

function canvas(w: number, h: number) {
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  return c;
}

function tex(c: HTMLCanvasElement) {
  const t = new THREE.CanvasTexture(c);
  t.anisotropy = 2;
  t.generateMipmaps = true;
  t.minFilter = THREE.LinearMipmapLinearFilter;
  t.needsUpdate = true;
  return t;
}

export interface PlaneSpec {
  texture: THREE.Texture;
  aspect: number;
}

/** large editorial typography plane */
export function textPlane(
  lines: string[],
  opts: { font?: 'serif' | 'sans' | 'mono'; italic?: boolean; size?: number; color?: string; label?: string; width?: number; align?: 'left' | 'center' } = {},
): PlaneSpec {
  const size = opts.size ?? 150;
  const fam = FONT[opts.font ?? 'serif'];
  const font = `${opts.italic ? 'italic ' : ''}400 ${size}px ${fam}`;
  const probe = canvas(4, 4).getContext('2d')!;
  probe.font = font;
  const maxW = Math.max(...lines.map((l) => probe.measureText(l).width));
  const pad = size * 0.35;
  const w = Math.min(2048, Math.ceil(opts.width ?? maxW + pad * 2));
  const lh = size * (opts.font === 'serif' || !opts.font ? 0.92 : 1.3);
  const labelH = opts.label ? 60 : 0;
  const h = Math.min(2048, Math.ceil(lines.length * lh + pad * 2 + labelH));
  const c = canvas(w, h);
  const ctx = c.getContext('2d')!;
  const scale = Math.min(1, (w - pad * 2) / maxW);
  if (opts.label) {
    ctx.font = `400 22px ${FONT.mono}`;
    ctx.fillStyle = COLOR.muted;
    ctx.fillText(opts.label, pad, pad * 0.6 + 20);
    ctx.fillStyle = 'rgba(244,241,234,0.25)';
    ctx.fillRect(pad, pad * 0.6 + 36, w - pad * 2, 1);
  }
  ctx.font = `${opts.italic ? 'italic ' : ''}400 ${size * scale}px ${fam}`;
  ctx.fillStyle = opts.color ?? COLOR.text;
  ctx.textBaseline = 'alphabetic';
  ctx.textAlign = opts.align ?? 'left';
  lines.forEach((l, i) => {
    const x = opts.align === 'center' ? w / 2 : pad;
    ctx.fillText(l, x, pad + labelH + (i + 0.78) * lh * scale);
  });
  return { texture: tex(c), aspect: w / h };
}

/** a memory placard like the ones in section 02 */
export function cardPlane(label: string, value: string, note = ''): PlaneSpec {
  const w = 720;
  const h = 460;
  const c = canvas(w, h);
  const ctx = c.getContext('2d')!;
  ctx.fillStyle = 'rgba(13,13,15,0.92)';
  ctx.fillRect(0, 0, w, h);
  ctx.strokeStyle = 'rgba(244,241,234,0.22)';
  ctx.lineWidth = 2;
  ctx.strokeRect(1, 1, w - 2, h - 2);
  ctx.font = `400 24px ${FONT.mono}`;
  ctx.fillStyle = COLOR.muted;
  ctx.fillText(label, 40, 64);
  ctx.font = `400 150px ${FONT.serif}`;
  ctx.fillStyle = COLOR.text;
  let fs = 150;
  while (ctx.measureText(value).width > w - 80 && fs > 40) {
    fs -= 8;
    ctx.font = `400 ${fs}px ${FONT.serif}`;
  }
  ctx.fillText(value, 40, 300);
  if (note) {
    ctx.font = `400 22px ${FONT.mono}`;
    ctx.fillStyle = COLOR.violet;
    ctx.fillText(note, 40, 410);
  }
  return { texture: tex(c), aspect: w / h };
}

/** pill button like the site's own buttons */
export function buttonPlane(text: string, filled = false, color = COLOR.text): PlaneSpec {
  const w = 900;
  const h = 240;
  const c = canvas(w, h);
  const ctx = c.getContext('2d')!;
  const r = h / 2 - 8;
  ctx.beginPath();
  ctx.roundRect(8, 8, w - 16, h - 16, r);
  if (filled) {
    ctx.fillStyle = color;
    ctx.fill();
  }
  ctx.strokeStyle = color;
  ctx.lineWidth = 3;
  ctx.stroke();
  ctx.font = `500 64px ${FONT.sans}`;
  ctx.letterSpacing = '14px';
  ctx.fillStyle = filled ? COLOR.bg : color;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(text, w / 2 + 7, h / 2 + 2);
  return { texture: tex(c), aspect: w / h };
}

/** an abstract "image" generated by the site's own design system */
export function artPlane(seed: number): PlaneSpec {
  const w = 512;
  const h = 640;
  const c = canvas(w, h);
  const ctx = c.getContext('2d')!;
  const rnd = mulberry(seed);
  ctx.fillStyle = '#0d0d0f';
  ctx.fillRect(0, 0, w, h);
  const hues = [COLOR.violet, COLOR.text, COLOR.cyan, '#2a2640'];
  // soft light fields
  for (let i = 0; i < 3; i++) {
    const g = ctx.createRadialGradient(rnd() * w, rnd() * h, 0, rnd() * w, rnd() * h, 200 + rnd() * 300);
    g.addColorStop(0, hues[(rnd() * hues.length) | 0] + '66');
    g.addColorStop(1, 'transparent');
    ctx.fillStyle = g;
    ctx.fillRect(0, 0, w, h);
  }
  // hairline contour study
  ctx.strokeStyle = 'rgba(244,241,234,0.35)';
  ctx.lineWidth = 1;
  const cx = w * (0.3 + rnd() * 0.4);
  const cy = h * (0.3 + rnd() * 0.4);
  for (let r = 20; r < 420; r += 14 + rnd() * 10) {
    ctx.beginPath();
    for (let a = 0; a <= Math.PI * 2 + 0.01; a += 0.05) {
      const k = r + Math.sin(a * 3 + r * 0.05) * r * 0.08;
      const x = cx + Math.cos(a) * k;
      const y = cy + Math.sin(a) * k * 1.2;
      a === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y);
    }
    ctx.stroke();
  }
  ctx.font = `400 18px ${FONT.mono}`;
  ctx.fillStyle = 'rgba(244,241,234,0.6)';
  ctx.fillText(`FIG. ${String(seed).padStart(2, '0')}`, 24, h - 28);
  ctx.strokeStyle = 'rgba(244,241,234,0.3)';
  ctx.strokeRect(0.5, 0.5, w - 1, h - 1);
  return { texture: tex(c), aspect: w / h };
}

/** single glyph sprite texture */
export function glyphTexture(ch: string, color = COLOR.text, font: 'serif' | 'mono' = 'serif') {
  const s = 128;
  const c = canvas(s, s);
  const ctx = c.getContext('2d')!;
  ctx.font = `400 ${font === 'serif' ? 110 : 80}px ${FONT[font]}`;
  ctx.fillStyle = color;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(ch, s / 2, s / 2 + 6);
  return tex(c);
}

export function mulberry(a: number) {
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function planeMesh(spec: PlaneSpec, height: number, opacity = 1) {
  const geo = new THREE.PlaneGeometry(height * spec.aspect, height);
  const mat = new THREE.MeshBasicMaterial({
    map: spec.texture,
    transparent: true,
    opacity,
    depthWrite: false,
    side: THREE.DoubleSide,
    fog: true,
  });
  return new THREE.Mesh(geo, mat);
}
